name: "RandomForestRegressor"
model_class: "src.models.rf.RandomForestModel"
fit_params:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 2
  min_samples_leaf: 1
  random_state: 42
prediction_params: {}
